OBS_LEN = 8
PRED_LEN = 12
NUM_WORKERS = 2

MLP_DIM = 64
H_DIM = 128
EMBEDDING_DIM = 32
BOTTLENECK_DIM = 32
NOISE_DIM = 16

SHARED_MAP_DIR = './img'
SHARED_MAP_NAME = 'North_shared_map.pkl'

DATASET_LIST = ['North_AM', 'North_NOON', 'North_PM']
NUM_ITERATIONS = 5000
NUM_EPOCHS = 10
G_LR = 2e-4
D_LR = 4e-4
G_STEPS = 2
D_STEPS = 1

MAX_PEDS = 1
BEST_K = 50
PRINT_EVERY = 500
NUM_SAMPLES = 20
NUM_SAMPLES_CHECK = 20

ATTN_L = 49
ATTN_D = 512
ATTN_D_DOWN = 16